apiVersion: v1
kind: Service
metadata:
  name: node
  labels:
    app: node
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  # Replace with the IP of your minikube node / master node
  externalIPs:
    - 192.168.99.100
  selector:
    app: node
    tier: backend