apiVersion: v1
kind: Service
metadata:
  name: node
  labels:
    app: node
    tier: backend
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 3000
  # Replace with the IP of your minikube node / master node
  selector:
    app: node
    tier: backend